"""added columns

Revision ID: 66ec7deecea7
Revises: dbc2b156e1da
Create Date: 2020-07-22 16:33:41.903387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ec7deecea7'
down_revision = 'dbc2b156e1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
